// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AcceptVersionRequest
 *
 * Request body for accepting a new version from evolution results.
 */
export type AcceptVersionRequest = {
    /**
     * Template
     */
    template: string;
};

/**
 * Body_import_cases_api_prompts__prompt_id__dataset_import_post
 */
export type BodyImportCasesApiPromptsPromptIdDatasetImportPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CaseResultResponse
 *
 * Evaluation result for a single test case.
 */
export type CaseResultResponse = {
    /**
     * Case Id
     */
    case_id: string;
    /**
     * Tier
     */
    tier?: string;
    /**
     * Score
     */
    score: number;
    /**
     * Passed
     */
    passed?: boolean;
    /**
     * Reason
     */
    reason?: string;
    /**
     * Expected
     */
    expected?: {
        [key: string]: unknown;
    } | null;
    /**
     * Actual Content
     */
    actual_content?: string | null;
    /**
     * Actual Tool Calls
     */
    actual_tool_calls?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Criteria Results
     */
    criteria_results?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * ChatRequest
 *
 * Request body for interactive chat playground.
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Variables
     */
    variables?: {
        [key: string]: unknown;
    };
    /**
     * Turn Limit
     */
    turn_limit?: number;
    /**
     * Cost Budget
     */
    cost_budget?: number;
};

/**
 * CreatePersonaRequest
 *
 * Request body for creating a new persona.
 */
export type CreatePersonaRequest = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Traits
     */
    traits: Array<string>;
    /**
     * Communication Style
     */
    communication_style: string;
    /**
     * Goal
     */
    goal: string;
    /**
     * Edge Cases
     */
    edge_cases?: Array<string> | null;
    /**
     * Behavior Criteria
     */
    behavior_criteria?: Array<string> | null;
    /**
     * Language
     */
    language?: string;
    /**
     * Channel
     */
    channel?: string;
};

/**
 * CreatePresetRequest
 *
 * Request body for creating a new preset.
 */
export type CreatePresetRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * CreatePromptRequest
 *
 * Request body for registering a new prompt.
 */
export type CreatePromptRequest = {
    /**
     * Id
     */
    id: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Template
     */
    template: string;
    /**
     * Variables
     */
    variables?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Tools
     */
    tools?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Tool Schemas
     */
    tool_schemas?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Mocks
     */
    mocks?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * EvolutionRunHistory
 *
 * Historical record of a completed evolution run.
 */
export type EvolutionRunHistory = {
    /**
     * Id
     */
    id: number;
    /**
     * Prompt Id
     */
    prompt_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Best Fitness Score
     */
    best_fitness_score: number | null;
    /**
     * Total Cost Usd
     */
    total_cost_usd: number;
    /**
     * Generations Completed
     */
    generations_completed: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Meta Model
     */
    meta_model: string;
    /**
     * Target Model
     */
    target_model: string;
};

/**
 * EvolutionRunRequest
 *
 * Request body for starting an evolution run.
 */
export type EvolutionRunRequest = {
    /**
     * Prompt Id
     */
    prompt_id: string;
    /**
     * Generations
     */
    generations?: number;
    /**
     * Islands
     */
    islands?: number;
    /**
     * Conversations Per Island
     */
    conversations_per_island?: number;
    /**
     * Budget Cap Usd
     */
    budget_cap_usd?: number | null;
    /**
     * Sample Size
     */
    sample_size?: number | null;
    /**
     * Sample Ratio
     */
    sample_ratio?: number | null;
    /**
     * Pr No Parents
     */
    pr_no_parents?: number | null;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * Structural Mutation Probability
     */
    structural_mutation_probability?: number | null;
    /**
     * N Seq
     */
    n_seq?: number | null;
    /**
     * Population Cap
     */
    population_cap?: number | null;
    /**
     * N Emigrate
     */
    n_emigrate?: number | null;
    /**
     * Reset Interval
     */
    reset_interval?: number | null;
    /**
     * N Reset
     */
    n_reset?: number | null;
    /**
     * N Top
     */
    n_top?: number | null;
    /**
     * Adaptive Sampling
     */
    adaptive_sampling?: boolean | null;
    /**
     * Adaptive Decay Constant
     */
    adaptive_decay_constant?: number | null;
    /**
     * Adaptive Min Rate
     */
    adaptive_min_rate?: number | null;
    /**
     * Checkpoint Interval
     */
    checkpoint_interval?: number | null;
    /**
     * Inference Temperature
     */
    inference_temperature?: number | null;
    /**
     * Top P
     */
    top_p?: number | null;
    /**
     * Top K
     */
    top_k?: number | null;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number | null;
    /**
     * Presence Penalty
     */
    presence_penalty?: number | null;
    /**
     * Meta Model
     */
    meta_model?: string | null;
    /**
     * Meta Provider
     */
    meta_provider?: string | null;
    /**
     * Target Model
     */
    target_model?: string | null;
    /**
     * Target Provider
     */
    target_provider?: string | null;
    /**
     * Judge Model
     */
    judge_model?: string | null;
    /**
     * Judge Provider
     */
    judge_provider?: string | null;
    /**
     * Meta Thinking Budget
     */
    meta_thinking_budget?: number | null;
    /**
     * Meta Thinking Level
     */
    meta_thinking_level?: string | null;
    /**
     * Target Thinking Budget
     */
    target_thinking_budget?: number | null;
    /**
     * Target Thinking Level
     */
    target_thinking_level?: string | null;
    /**
     * Judge Thinking Budget
     */
    judge_thinking_budget?: number | null;
    /**
     * Judge Thinking Level
     */
    judge_thinking_level?: string | null;
};

/**
 * EvolutionRunStatus
 *
 * Status of a running evolution.
 */
export type EvolutionRunStatus = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Prompt Id
     */
    prompt_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Meta Model
     */
    meta_model?: string | null;
    /**
     * Meta Provider
     */
    meta_provider?: string | null;
    /**
     * Target Model
     */
    target_model?: string | null;
    /**
     * Target Provider
     */
    target_provider?: string | null;
    /**
     * Judge Model
     */
    judge_model?: string | null;
    /**
     * Judge Provider
     */
    judge_provider?: string | null;
    /**
     * Hyperparameters
     */
    hyperparameters?: {
        [key: string]: unknown;
    } | null;
};

/**
 * FormatGuideResponse
 *
 * Response representation of a tool format guide.
 */
export type FormatGuideResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Prompt Id
     */
    prompt_id: string;
    /**
     * Tool Name
     */
    tool_name: string;
    /**
     * Examples
     */
    examples: Array<string>;
};

/**
 * GenerateSampleRequest
 *
 * Request body for generating a sample mock response.
 */
export type GenerateSampleRequest = {
    /**
     * Tool Name
     */
    tool_name: string;
    /**
     * Scenario Type
     */
    scenario_type?: string;
};

/**
 * GenerateSampleResponse
 *
 * Response from sample generation endpoint.
 */
export type GenerateSampleResponse = {
    /**
     * Sample
     */
    sample: string;
    /**
     * Scenario Type
     */
    scenario_type: string;
};

/**
 * GenerationConfig
 *
 * Generation hyperparameters for LLM calls.
 */
export type GenerationConfig = {
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Max Tokens
     */
    max_tokens?: number;
    /**
     * Top P
     */
    top_p?: number | null;
    /**
     * Top K
     */
    top_k?: number | null;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number | null;
    /**
     * Presence Penalty
     */
    presence_penalty?: number | null;
};

/**
 * GenerationRecordResponse
 *
 * Per-generation metrics for fitness progression chart.
 */
export type GenerationRecordResponse = {
    /**
     * Generation
     */
    generation: number;
    /**
     * Best Fitness
     */
    best_fitness: number;
    /**
     * Avg Fitness
     */
    avg_fitness: number;
    /**
     * Best Normalized
     */
    best_normalized?: number;
    /**
     * Avg Normalized
     */
    avg_normalized?: number;
    /**
     * Candidates Evaluated
     */
    candidates_evaluated?: number;
    /**
     * Cost Summary
     */
    cost_summary?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportPersonasResponse
 *
 * Response from persona import operation.
 */
export type ImportPersonasResponse = {
    /**
     * Added Count
     */
    added_count: number;
    /**
     * Skipped Count
     */
    skipped_count: number;
    /**
     * Total
     */
    total: number;
};

/**
 * LineageEventResponse
 *
 * A single lineage event from the evolution run.
 */
export type LineageEventResponse = {
    /**
     * Candidate Id
     */
    candidate_id: string;
    /**
     * Parent Ids
     */
    parent_ids?: Array<string>;
    /**
     * Generation
     */
    generation: number;
    /**
     * Island
     */
    island?: number;
    /**
     * Fitness Score
     */
    fitness_score?: number;
    /**
     * Normalized Score
     */
    normalized_score?: number;
    /**
     * Rejected
     */
    rejected?: boolean;
    /**
     * Mutation Type
     */
    mutation_type?: string;
    /**
     * Survived
     */
    survived?: boolean;
    /**
     * Template
     */
    template?: string | null;
};

/**
 * ModelInfo
 *
 * Normalized model metadata returned by the /api/models endpoint.
 *
 * Fields:
 * id: Value passed to model= in API calls (e.g. "gemini-2.5-pro").
 * name: Human-readable display name (e.g. "Gemini 2.5 Pro").
 * context_length: Maximum input token limit, if known.
 * input_price_per_mtok: USD per 1M input tokens (OpenRouter only).
 * output_price_per_mtok: USD per 1M output tokens (OpenRouter only).
 * provider: Source provider ("openrouter" or "gemini").
 */
export type ModelInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Context Length
     */
    context_length?: number | null;
    /**
     * Input Price Per Mtok
     */
    input_price_per_mtok?: number | null;
    /**
     * Output Price Per Mtok
     */
    output_price_per_mtok?: number | null;
    /**
     * Provider
     */
    provider: string;
};

/**
 * PersonaProfileResponse
 *
 * Response representation of a persona profile.
 */
export type PersonaProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Traits
     */
    traits: Array<string>;
    /**
     * Communication Style
     */
    communication_style: string;
    /**
     * Goal
     */
    goal: string;
    /**
     * Edge Cases
     */
    edge_cases?: Array<string>;
    /**
     * Behavior Criteria
     */
    behavior_criteria?: Array<string>;
    /**
     * Language
     */
    language?: string;
    /**
     * Channel
     */
    channel?: string;
};

/**
 * PlaygroundConfigResponse
 *
 * Response with playground config (turn_limit, budget) for a prompt.
 */
export type PlaygroundConfigResponse = {
    /**
     * Turn Limit
     */
    turn_limit?: number | null;
    /**
     * Budget
     */
    budget?: number | null;
};

/**
 * PlaygroundConfigUpdateRequest
 *
 * Request body for updating playground config (turn_limit, budget).
 */
export type PlaygroundConfigUpdateRequest = {
    /**
     * Turn Limit
     */
    turn_limit?: number | null;
    /**
     * Budget
     */
    budget?: number | null;
};

/**
 * PlaygroundVariablesResponse
 *
 * Response with saved variable values for a prompt.
 */
export type PlaygroundVariablesResponse = {
    /**
     * Prompt Id
     */
    prompt_id: string;
    /**
     * Variables
     */
    variables: {
        [key: string]: string;
    };
};

/**
 * PlaygroundVariablesUpdateRequest
 *
 * Request body for saving playground variable values.
 */
export type PlaygroundVariablesUpdateRequest = {
    /**
     * Variables
     */
    variables: {
        [key: string]: string;
    };
};

/**
 * PresetResponse
 *
 * Response representation of a config or evolution preset.
 */
export type PresetResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PromptConfigResponse
 *
 * Response from GET/PUT /api/prompts/{id}/config.
 *
 * Contains effective (merged) values per role and the raw overrides dict
 * so the UI can show Global/Override provenance badges.
 */
export type PromptConfigResponse = {
    meta: RoleConfigResponse;
    target: RoleConfigResponse;
    judge: RoleConfigResponse;
    tool_mocker: ToolMockerConfigResponse;
    /**
     * Overrides
     */
    overrides: {
        [key: string]: unknown;
    };
};

/**
 * PromptConfigSchema
 *
 * Schema for config.json sidecar file.
 *
 * Contains per-prompt configuration overrides that get merged
 * onto the global GeneConfig via load_prompt_config.
 *
 * All fields are optional (None = use global default). The to_json()
 * method uses exclude_none to keep config.json files clean and
 * backward-compatible with existing prompts.
 */
export type PromptConfigSchema = {
    /**
     * Meta Model
     */
    meta_model?: string | null;
    /**
     * Target Model
     */
    target_model?: string | null;
    /**
     * Judge Model
     */
    judge_model?: string | null;
    /**
     * Meta Provider
     */
    meta_provider?: string | null;
    /**
     * Target Provider
     */
    target_provider?: string | null;
    /**
     * Judge Provider
     */
    judge_provider?: string | null;
    /**
     * Meta Temperature
     */
    meta_temperature?: number | null;
    /**
     * Target Temperature
     */
    target_temperature?: number | null;
    /**
     * Judge Temperature
     */
    judge_temperature?: number | null;
    /**
     * Meta Thinking Budget
     */
    meta_thinking_budget?: number | null;
    /**
     * Target Thinking Budget
     */
    target_thinking_budget?: number | null;
    /**
     * Judge Thinking Budget
     */
    judge_thinking_budget?: number | null;
    /**
     * Tool Mocker Mode
     */
    tool_mocker_mode?: string | null;
    /**
     * Tool Mocker Provider
     */
    tool_mocker_provider?: string | null;
    /**
     * Tool Mocker Model
     */
    tool_mocker_model?: string | null;
    generation?: GenerationConfig | null;
};

/**
 * PromptDetail
 *
 * Full prompt detail including template content.
 */
export type PromptDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Template Variables
     */
    template_variables: Array<string>;
    /**
     * Anchor Variables
     */
    anchor_variables: Array<string>;
    /**
     * Template
     */
    template: string;
    /**
     * Tools
     */
    tools?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Tool Schemas
     */
    tool_schemas?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Mocks
     */
    mocks?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Variable Definitions
     */
    variable_definitions?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * PromptSummary
 *
 * Summary representation of a registered prompt.
 */
export type PromptSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Template Variables
     */
    template_variables: Array<string>;
    /**
     * Anchor Variables
     */
    anchor_variables: Array<string>;
};

/**
 * PromptVersionResponse
 *
 * Response representation of a prompt version.
 */
export type PromptVersionResponse = {
    /**
     * Version
     */
    version: number;
    /**
     * Template
     */
    template: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ReviewDecision
 *
 * Per-conversation approve/reject decision for synthesis review.
 */
export type ReviewDecision = {
    /**
     * Conversation Index
     */
    conversation_index: number;
    /**
     * Action
     */
    action: 'approve' | 'reject';
    /**
     * Edits
     */
    edits?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ReviewRequest
 *
 * Request body for submitting review decisions on synthesized conversations.
 */
export type ReviewRequest = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Decisions
     */
    decisions: Array<ReviewDecision>;
};

/**
 * ReviewResponse
 *
 * Response from review endpoint with persist counts.
 */
export type ReviewResponse = {
    /**
     * Approved
     */
    approved: number;
    /**
     * Rejected
     */
    rejected: number;
    /**
     * Case Ids
     */
    case_ids: Array<string>;
};

/**
 * RoleConfig
 *
 * Configuration for a single role (meta/target/judge).
 */
export type RoleConfig = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Has Key
     */
    has_key: boolean;
    /**
     * Key Hint
     */
    key_hint?: string;
    /**
     * Thinking Budget
     */
    thinking_budget?: number | null;
};

/**
 * RoleConfigResponse
 *
 * Effective configuration for a single role (meta/target/judge) with merged values.
 */
export type RoleConfigResponse = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Temperature
     */
    temperature: number | null;
    /**
     * Thinking Budget
     */
    thinking_budget: number | null;
};

/**
 * RunResultsResponse
 *
 * Full results for a completed evolution run, used by visualization components.
 */
export type RunResultsResponse = {
    /**
     * Prompt Id
     */
    prompt_id?: string | null;
    /**
     * Lineage Events
     */
    lineage_events?: Array<LineageEventResponse>;
    /**
     * Case Results
     */
    case_results?: Array<CaseResultResponse>;
    /**
     * Seed Case Results
     */
    seed_case_results?: Array<CaseResultResponse>;
    /**
     * Generation Records
     */
    generation_records?: Array<GenerationRecordResponse>;
    /**
     * Best Candidate Id
     */
    best_candidate_id?: string | null;
    /**
     * Best Template
     */
    best_template?: string | null;
    /**
     * Total Cost Usd
     */
    total_cost_usd?: number;
    /**
     * Best Fitness Score
     */
    best_fitness_score?: number | null;
    /**
     * Best Normalized Score
     */
    best_normalized_score?: number | null;
    /**
     * Generations Completed
     */
    generations_completed?: number;
    /**
     * Termination Reason
     */
    termination_reason?: string | null;
    /**
     * Meta Model
     */
    meta_model?: string | null;
    /**
     * Target Model
     */
    target_model?: string | null;
    /**
     * Judge Model
     */
    judge_model?: string | null;
    /**
     * Meta Provider
     */
    meta_provider?: string | null;
    /**
     * Target Provider
     */
    target_provider?: string | null;
    /**
     * Judge Provider
     */
    judge_provider?: string | null;
    /**
     * Hyperparameters
     */
    hyperparameters?: {
        [key: string]: unknown;
    } | null;
};

/**
 * SettingsResponse
 *
 * Response from GET /api/settings.
 */
export type SettingsResponse = {
    meta: RoleConfig;
    target: RoleConfig;
    judge: RoleConfig;
    /**
     * Concurrency Limit
     */
    concurrency_limit: number;
    /**
     * Generation
     */
    generation: {
        [key: string]: unknown;
    };
    /**
     * Providers
     */
    providers: Array<string>;
    /**
     * Has Db Keys
     */
    has_db_keys?: boolean;
};

/**
 * SettingsUpdateRequest
 *
 * Request body for PUT /api/settings. All fields optional for partial update.
 */
export type SettingsUpdateRequest = {
    /**
     * Meta Provider
     */
    meta_provider?: string | null;
    /**
     * Meta Model
     */
    meta_model?: string | null;
    /**
     * Target Provider
     */
    target_provider?: string | null;
    /**
     * Target Model
     */
    target_model?: string | null;
    /**
     * Judge Provider
     */
    judge_provider?: string | null;
    /**
     * Judge Model
     */
    judge_model?: string | null;
    /**
     * Openrouter Api Key
     */
    openrouter_api_key?: string | null;
    /**
     * Gemini Api Key
     */
    gemini_api_key?: string | null;
    /**
     * Openai Api Key
     */
    openai_api_key?: string | null;
    /**
     * Concurrency Limit
     */
    concurrency_limit?: number | null;
    /**
     * Generation
     */
    generation?: {
        [key: string]: unknown;
    } | null;
    /**
     * Meta Thinking Budget
     */
    meta_thinking_budget?: number | null;
    /**
     * Target Thinking Budget
     */
    target_thinking_budget?: number | null;
    /**
     * Judge Thinking Budget
     */
    judge_thinking_budget?: number | null;
};

/**
 * SynthesizeRequest
 *
 * Request body for starting a synthesis run.
 */
export type SynthesizeRequest = {
    /**
     * Persona Ids
     */
    persona_ids?: Array<string> | null;
    /**
     * Num Conversations
     */
    num_conversations?: number;
    /**
     * Max Turns
     */
    max_turns?: number;
    /**
     * Scenario Context
     */
    scenario_context?: string | null;
    /**
     * Review Mode
     */
    review_mode?: boolean;
};

/**
 * SynthesizeResponse
 *
 * Response from starting a synthesis run.
 */
export type SynthesizeResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Total Personas
     */
    total_personas: number;
    /**
     * Num Conversations
     */
    num_conversations: number;
};

/**
 * TestCaseCreateRequest
 *
 * Request body for creating a new test case.
 */
export type TestCaseCreateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Chat History
     */
    chat_history?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Variables
     */
    variables?: {
        [key: string]: unknown;
    };
    /**
     * Tools
     */
    tools?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Expected Output
     */
    expected_output?: {
        [key: string]: unknown;
    } | null;
    /**
     * Tier
     */
    tier?: string;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * TestCaseResponse
 *
 * Response representation of a test case.
 */
export type TestCaseResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Tier
     */
    tier: string;
    /**
     * Variables
     */
    variables: {
        [key: string]: unknown;
    };
    /**
     * Expected Output
     */
    expected_output: {
        [key: string]: unknown;
    } | null;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Chat History
     */
    chat_history: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Tools
     */
    tools?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Validation Warnings
     */
    validation_warnings?: Array<string>;
};

/**
 * TestCaseUpdateRequest
 *
 * Request body for updating an existing test case. All fields optional.
 */
export type TestCaseUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Chat History
     */
    chat_history?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Variables
     */
    variables?: {
        [key: string]: unknown;
    } | null;
    /**
     * Tools
     */
    tools?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Expected Output
     */
    expected_output?: {
        [key: string]: unknown;
    } | null;
    /**
     * Tier
     */
    tier?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
};

/**
 * TestConnectionRequest
 *
 * Request body for POST /api/settings/test-connection.
 */
export type TestConnectionRequest = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Api Key
     */
    api_key: string;
};

/**
 * TestConnectionResponse
 *
 * Response from POST /api/settings/test-connection.
 */
export type TestConnectionResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * ToolMockerConfigResponse
 *
 * Configuration for the Tool Mocker role (static YAML or LLM-based).
 */
export type ToolMockerConfigResponse = {
    /**
     * Mode
     */
    mode: string;
    /**
     * Provider
     */
    provider: string | null;
    /**
     * Model
     */
    model: string | null;
};

/**
 * UpdatePersonaRequest
 *
 * Request body for updating a persona. All fields optional for partial update.
 */
export type UpdatePersonaRequest = {
    /**
     * Role
     */
    role?: string | null;
    /**
     * Traits
     */
    traits?: Array<string> | null;
    /**
     * Communication Style
     */
    communication_style?: string | null;
    /**
     * Goal
     */
    goal?: string | null;
    /**
     * Edge Cases
     */
    edge_cases?: Array<string> | null;
    /**
     * Behavior Criteria
     */
    behavior_criteria?: Array<string> | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Channel
     */
    channel?: string | null;
};

/**
 * UpdatePresetRequest
 *
 * Request body for updating a preset. All fields optional.
 */
export type UpdatePresetRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Is Default
     */
    is_default?: boolean | null;
};

/**
 * UpdateTemplateRequest
 *
 * Request body for updating a prompt's template.
 */
export type UpdateTemplateRequest = {
    /**
     * Template
     */
    template: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WizardGenerateRequest
 *
 * Request body for wizard template generation.
 */
export type WizardGenerateRequest = {
    /**
     * Id
     */
    id: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Variables
     */
    variables?: Array<WizardVariable>;
    /**
     * Constraints
     */
    constraints?: string | null;
    /**
     * Behaviors
     */
    behaviors?: string | null;
    /**
     * Include Tools
     */
    include_tools?: boolean;
    /**
     * Tool Descriptions
     */
    tool_descriptions?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Channel
     */
    channel?: string | null;
};

/**
 * WizardGenerateResponse
 *
 * Response from wizard template generation.
 */
export type WizardGenerateResponse = {
    /**
     * Yaml Template
     */
    yaml_template: string;
};

/**
 * WizardVariable
 *
 * Variable definition from wizard form.
 */
export type WizardVariable = {
    /**
     * Name
     */
    name: string;
    /**
     * Var Type
     */
    var_type?: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Anchor
     */
    is_anchor?: boolean;
    /**
     * Examples
     */
    examples?: Array<unknown> | null;
    /**
     * Items Schema
     */
    items_schema?: Array<WizardVariable> | null;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListPromptsApiPromptsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/prompts/';
};

export type ListPromptsApiPromptsGetResponses = {
    /**
     * Response List Prompts Api Prompts  Get
     *
     * Successful Response
     */
    200: Array<PromptSummary>;
};

export type ListPromptsApiPromptsGetResponse = ListPromptsApiPromptsGetResponses[keyof ListPromptsApiPromptsGetResponses];

export type CreatePromptApiPromptsPostData = {
    body: CreatePromptRequest;
    path?: never;
    query?: never;
    url: '/api/prompts/';
};

export type CreatePromptApiPromptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePromptApiPromptsPostError = CreatePromptApiPromptsPostErrors[keyof CreatePromptApiPromptsPostErrors];

export type CreatePromptApiPromptsPostResponses = {
    /**
     * Successful Response
     */
    201: PromptSummary;
};

export type CreatePromptApiPromptsPostResponse = CreatePromptApiPromptsPostResponses[keyof CreatePromptApiPromptsPostResponses];

export type GetPromptConfigApiPromptsPromptIdConfigGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/config';
};

export type GetPromptConfigApiPromptsPromptIdConfigGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPromptConfigApiPromptsPromptIdConfigGetError = GetPromptConfigApiPromptsPromptIdConfigGetErrors[keyof GetPromptConfigApiPromptsPromptIdConfigGetErrors];

export type GetPromptConfigApiPromptsPromptIdConfigGetResponses = {
    /**
     * Successful Response
     */
    200: PromptConfigResponse;
};

export type GetPromptConfigApiPromptsPromptIdConfigGetResponse = GetPromptConfigApiPromptsPromptIdConfigGetResponses[keyof GetPromptConfigApiPromptsPromptIdConfigGetResponses];

export type UpdatePromptConfigApiPromptsPromptIdConfigPutData = {
    body: PromptConfigSchema;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/config';
};

export type UpdatePromptConfigApiPromptsPromptIdConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePromptConfigApiPromptsPromptIdConfigPutError = UpdatePromptConfigApiPromptsPromptIdConfigPutErrors[keyof UpdatePromptConfigApiPromptsPromptIdConfigPutErrors];

export type UpdatePromptConfigApiPromptsPromptIdConfigPutResponses = {
    /**
     * Successful Response
     */
    200: PromptConfigResponse;
};

export type UpdatePromptConfigApiPromptsPromptIdConfigPutResponse = UpdatePromptConfigApiPromptsPromptIdConfigPutResponses[keyof UpdatePromptConfigApiPromptsPromptIdConfigPutResponses];

export type GetPromptApiPromptsPromptIdGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}';
};

export type GetPromptApiPromptsPromptIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPromptApiPromptsPromptIdGetError = GetPromptApiPromptsPromptIdGetErrors[keyof GetPromptApiPromptsPromptIdGetErrors];

export type GetPromptApiPromptsPromptIdGetResponses = {
    /**
     * Successful Response
     */
    200: PromptDetail;
};

export type GetPromptApiPromptsPromptIdGetResponse = GetPromptApiPromptsPromptIdGetResponses[keyof GetPromptApiPromptsPromptIdGetResponses];

export type UpdateTemplateApiPromptsPromptIdTemplatePutData = {
    body: UpdateTemplateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/template';
};

export type UpdateTemplateApiPromptsPromptIdTemplatePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTemplateApiPromptsPromptIdTemplatePutError = UpdateTemplateApiPromptsPromptIdTemplatePutErrors[keyof UpdateTemplateApiPromptsPromptIdTemplatePutErrors];

export type UpdateTemplateApiPromptsPromptIdTemplatePutResponses = {
    /**
     * Successful Response
     */
    200: PromptSummary;
};

export type UpdateTemplateApiPromptsPromptIdTemplatePutResponse = UpdateTemplateApiPromptsPromptIdTemplatePutResponses[keyof UpdateTemplateApiPromptsPromptIdTemplatePutResponses];

export type ListVersionsApiPromptsPromptIdVersionsGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/versions';
};

export type ListVersionsApiPromptsPromptIdVersionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVersionsApiPromptsPromptIdVersionsGetError = ListVersionsApiPromptsPromptIdVersionsGetErrors[keyof ListVersionsApiPromptsPromptIdVersionsGetErrors];

export type ListVersionsApiPromptsPromptIdVersionsGetResponses = {
    /**
     * Response List Versions Api Prompts  Prompt Id  Versions Get
     *
     * Successful Response
     */
    200: Array<PromptVersionResponse>;
};

export type ListVersionsApiPromptsPromptIdVersionsGetResponse = ListVersionsApiPromptsPromptIdVersionsGetResponses[keyof ListVersionsApiPromptsPromptIdVersionsGetResponses];

export type GetVersionApiPromptsPromptIdVersionsVersionGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/versions/{version}';
};

export type GetVersionApiPromptsPromptIdVersionsVersionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVersionApiPromptsPromptIdVersionsVersionGetError = GetVersionApiPromptsPromptIdVersionsVersionGetErrors[keyof GetVersionApiPromptsPromptIdVersionsVersionGetErrors];

export type GetVersionApiPromptsPromptIdVersionsVersionGetResponses = {
    /**
     * Successful Response
     */
    200: PromptVersionResponse;
};

export type GetVersionApiPromptsPromptIdVersionsVersionGetResponse = GetVersionApiPromptsPromptIdVersionsVersionGetResponses[keyof GetVersionApiPromptsPromptIdVersionsVersionGetResponses];

export type ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/versions/{version}/activate';
};

export type ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutError = ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutErrors[keyof ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutErrors];

export type ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutResponses = {
    /**
     * Successful Response
     */
    200: PromptVersionResponse;
};

export type ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutResponse = ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutResponses[keyof ActivateVersionApiPromptsPromptIdVersionsVersionActivatePutResponses];

export type AcceptVersionApiPromptsPromptIdVersionsAcceptPostData = {
    body: AcceptVersionRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/versions/accept';
};

export type AcceptVersionApiPromptsPromptIdVersionsAcceptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptVersionApiPromptsPromptIdVersionsAcceptPostError = AcceptVersionApiPromptsPromptIdVersionsAcceptPostErrors[keyof AcceptVersionApiPromptsPromptIdVersionsAcceptPostErrors];

export type AcceptVersionApiPromptsPromptIdVersionsAcceptPostResponses = {
    /**
     * Successful Response
     */
    201: PromptVersionResponse;
};

export type AcceptVersionApiPromptsPromptIdVersionsAcceptPostResponse = AcceptVersionApiPromptsPromptIdVersionsAcceptPostResponses[keyof AcceptVersionApiPromptsPromptIdVersionsAcceptPostResponses];

export type ListCasesApiPromptsPromptIdDatasetGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/dataset';
};

export type ListCasesApiPromptsPromptIdDatasetGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCasesApiPromptsPromptIdDatasetGetError = ListCasesApiPromptsPromptIdDatasetGetErrors[keyof ListCasesApiPromptsPromptIdDatasetGetErrors];

export type ListCasesApiPromptsPromptIdDatasetGetResponses = {
    /**
     * Response List Cases Api Prompts  Prompt Id  Dataset Get
     *
     * Successful Response
     */
    200: Array<TestCaseResponse>;
};

export type ListCasesApiPromptsPromptIdDatasetGetResponse = ListCasesApiPromptsPromptIdDatasetGetResponses[keyof ListCasesApiPromptsPromptIdDatasetGetResponses];

export type AddCaseApiPromptsPromptIdDatasetPostData = {
    body: TestCaseCreateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/dataset';
};

export type AddCaseApiPromptsPromptIdDatasetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCaseApiPromptsPromptIdDatasetPostError = AddCaseApiPromptsPromptIdDatasetPostErrors[keyof AddCaseApiPromptsPromptIdDatasetPostErrors];

export type AddCaseApiPromptsPromptIdDatasetPostResponses = {
    /**
     * Successful Response
     */
    201: TestCaseResponse;
};

export type AddCaseApiPromptsPromptIdDatasetPostResponse = AddCaseApiPromptsPromptIdDatasetPostResponses[keyof AddCaseApiPromptsPromptIdDatasetPostResponses];

export type DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/dataset/{case_id}';
};

export type DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteError = DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteErrors[keyof DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteErrors];

export type DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteResponse = DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteResponses[keyof DeleteCaseApiPromptsPromptIdDatasetCaseIdDeleteResponses];

export type GetCaseApiPromptsPromptIdDatasetCaseIdGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/dataset/{case_id}';
};

export type GetCaseApiPromptsPromptIdDatasetCaseIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCaseApiPromptsPromptIdDatasetCaseIdGetError = GetCaseApiPromptsPromptIdDatasetCaseIdGetErrors[keyof GetCaseApiPromptsPromptIdDatasetCaseIdGetErrors];

export type GetCaseApiPromptsPromptIdDatasetCaseIdGetResponses = {
    /**
     * Successful Response
     */
    200: TestCaseResponse;
};

export type GetCaseApiPromptsPromptIdDatasetCaseIdGetResponse = GetCaseApiPromptsPromptIdDatasetCaseIdGetResponses[keyof GetCaseApiPromptsPromptIdDatasetCaseIdGetResponses];

export type UpdateCaseApiPromptsPromptIdDatasetCaseIdPutData = {
    body: TestCaseUpdateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/dataset/{case_id}';
};

export type UpdateCaseApiPromptsPromptIdDatasetCaseIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCaseApiPromptsPromptIdDatasetCaseIdPutError = UpdateCaseApiPromptsPromptIdDatasetCaseIdPutErrors[keyof UpdateCaseApiPromptsPromptIdDatasetCaseIdPutErrors];

export type UpdateCaseApiPromptsPromptIdDatasetCaseIdPutResponses = {
    /**
     * Successful Response
     */
    200: TestCaseResponse;
};

export type UpdateCaseApiPromptsPromptIdDatasetCaseIdPutResponse = UpdateCaseApiPromptsPromptIdDatasetCaseIdPutResponses[keyof UpdateCaseApiPromptsPromptIdDatasetCaseIdPutResponses];

export type ImportCasesApiPromptsPromptIdDatasetImportPostData = {
    body: BodyImportCasesApiPromptsPromptIdDatasetImportPost;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/dataset/import';
};

export type ImportCasesApiPromptsPromptIdDatasetImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportCasesApiPromptsPromptIdDatasetImportPostError = ImportCasesApiPromptsPromptIdDatasetImportPostErrors[keyof ImportCasesApiPromptsPromptIdDatasetImportPostErrors];

export type ImportCasesApiPromptsPromptIdDatasetImportPostResponses = {
    /**
     * Response Import Cases Api Prompts  Prompt Id  Dataset Import Post
     *
     * Successful Response
     */
    200: Array<TestCaseResponse>;
};

export type ImportCasesApiPromptsPromptIdDatasetImportPostResponse = ImportCasesApiPromptsPromptIdDatasetImportPostResponses[keyof ImportCasesApiPromptsPromptIdDatasetImportPostResponses];

export type StartEvolutionApiEvolutionStartPostData = {
    body: EvolutionRunRequest;
    path?: never;
    query?: never;
    url: '/api/evolution/start';
};

export type StartEvolutionApiEvolutionStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartEvolutionApiEvolutionStartPostError = StartEvolutionApiEvolutionStartPostErrors[keyof StartEvolutionApiEvolutionStartPostErrors];

export type StartEvolutionApiEvolutionStartPostResponses = {
    /**
     * Successful Response
     */
    200: EvolutionRunStatus;
};

export type StartEvolutionApiEvolutionStartPostResponse = StartEvolutionApiEvolutionStartPostResponses[keyof StartEvolutionApiEvolutionStartPostResponses];

export type ListActiveRunsApiEvolutionActiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/evolution/active';
};

export type ListActiveRunsApiEvolutionActiveGetResponses = {
    /**
     * Response List Active Runs Api Evolution Active Get
     *
     * Successful Response
     */
    200: Array<EvolutionRunStatus>;
};

export type ListActiveRunsApiEvolutionActiveGetResponse = ListActiveRunsApiEvolutionActiveGetResponses[keyof ListActiveRunsApiEvolutionActiveGetResponses];

export type StopEvolutionApiEvolutionRunIdStopPostData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/evolution/{run_id}/stop';
};

export type StopEvolutionApiEvolutionRunIdStopPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopEvolutionApiEvolutionRunIdStopPostError = StopEvolutionApiEvolutionRunIdStopPostErrors[keyof StopEvolutionApiEvolutionRunIdStopPostErrors];

export type StopEvolutionApiEvolutionRunIdStopPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRunStatusApiEvolutionRunIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/evolution/{run_id}/status';
};

export type GetRunStatusApiEvolutionRunIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunStatusApiEvolutionRunIdStatusGetError = GetRunStatusApiEvolutionRunIdStatusGetErrors[keyof GetRunStatusApiEvolutionRunIdStatusGetErrors];

export type GetRunStatusApiEvolutionRunIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: EvolutionRunStatus;
};

export type GetRunStatusApiEvolutionRunIdStatusGetResponse = GetRunStatusApiEvolutionRunIdStatusGetResponses[keyof GetRunStatusApiEvolutionRunIdStatusGetResponses];

export type GetHistoryApiHistoryPromptIdGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/history/{prompt_id}';
};

export type GetHistoryApiHistoryPromptIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryApiHistoryPromptIdGetError = GetHistoryApiHistoryPromptIdGetErrors[keyof GetHistoryApiHistoryPromptIdGetErrors];

export type GetHistoryApiHistoryPromptIdGetResponses = {
    /**
     * Response Get History Api History  Prompt Id  Get
     *
     * Successful Response
     */
    200: Array<EvolutionRunHistory>;
};

export type GetHistoryApiHistoryPromptIdGetResponse = GetHistoryApiHistoryPromptIdGetResponses[keyof GetHistoryApiHistoryPromptIdGetResponses];

export type GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetData = {
    body?: never;
    path: {
        /**
         * Run Uuid
         */
        run_uuid: string;
    };
    query?: never;
    url: '/api/history/run/by-uuid/{run_uuid}/results';
};

export type GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetError = GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetErrors[keyof GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetErrors];

export type GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetResponses = {
    /**
     * Successful Response
     */
    200: RunResultsResponse;
};

export type GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetResponse = GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetResponses[keyof GetRunResultsByUuidApiHistoryRunByUuidRunUuidResultsGetResponses];

export type GetRunDetailApiHistoryRunRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/api/history/run/{run_id}';
};

export type GetRunDetailApiHistoryRunRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunDetailApiHistoryRunRunIdGetError = GetRunDetailApiHistoryRunRunIdGetErrors[keyof GetRunDetailApiHistoryRunRunIdGetErrors];

export type GetRunDetailApiHistoryRunRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: EvolutionRunHistory;
};

export type GetRunDetailApiHistoryRunRunIdGetResponse = GetRunDetailApiHistoryRunRunIdGetResponses[keyof GetRunDetailApiHistoryRunRunIdGetResponses];

export type GetRunResultsApiHistoryRunRunIdResultsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/api/history/run/{run_id}/results';
};

export type GetRunResultsApiHistoryRunRunIdResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunResultsApiHistoryRunRunIdResultsGetError = GetRunResultsApiHistoryRunRunIdResultsGetErrors[keyof GetRunResultsApiHistoryRunRunIdResultsGetErrors];

export type GetRunResultsApiHistoryRunRunIdResultsGetResponses = {
    /**
     * Successful Response
     */
    200: RunResultsResponse;
};

export type GetRunResultsApiHistoryRunRunIdResultsGetResponse = GetRunResultsApiHistoryRunRunIdResultsGetResponses[keyof GetRunResultsApiHistoryRunRunIdResultsGetResponses];

export type ListModelsApiModelsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Provider
         *
         * Provider name: 'openrouter', 'gemini', or 'openai'
         */
        provider: string;
    };
    url: '/api/models/';
};

export type ListModelsApiModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelsApiModelsGetError = ListModelsApiModelsGetErrors[keyof ListModelsApiModelsGetErrors];

export type ListModelsApiModelsGetResponses = {
    /**
     * Response List Models Api Models  Get
     *
     * Successful Response
     */
    200: Array<ModelInfo>;
};

export type ListModelsApiModelsGetResponse = ListModelsApiModelsGetResponses[keyof ListModelsApiModelsGetResponses];

export type GenerateTemplateApiWizardGeneratePostData = {
    body: WizardGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/wizard/generate';
};

export type GenerateTemplateApiWizardGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTemplateApiWizardGeneratePostError = GenerateTemplateApiWizardGeneratePostErrors[keyof GenerateTemplateApiWizardGeneratePostErrors];

export type GenerateTemplateApiWizardGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: WizardGenerateResponse;
};

export type GenerateTemplateApiWizardGeneratePostResponse = GenerateTemplateApiWizardGeneratePostResponses[keyof GenerateTemplateApiWizardGeneratePostResponses];

export type StartSynthesisApiPromptsPromptIdSynthesizePostData = {
    body: SynthesizeRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/synthesize';
};

export type StartSynthesisApiPromptsPromptIdSynthesizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartSynthesisApiPromptsPromptIdSynthesizePostError = StartSynthesisApiPromptsPromptIdSynthesizePostErrors[keyof StartSynthesisApiPromptsPromptIdSynthesizePostErrors];

export type StartSynthesisApiPromptsPromptIdSynthesizePostResponses = {
    /**
     * Successful Response
     */
    200: SynthesizeResponse;
};

export type StartSynthesisApiPromptsPromptIdSynthesizePostResponse = StartSynthesisApiPromptsPromptIdSynthesizePostResponses[keyof StartSynthesisApiPromptsPromptIdSynthesizePostResponses];

export type ReviewConversationsApiPromptsPromptIdReviewPostData = {
    body: ReviewRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/review';
};

export type ReviewConversationsApiPromptsPromptIdReviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewConversationsApiPromptsPromptIdReviewPostError = ReviewConversationsApiPromptsPromptIdReviewPostErrors[keyof ReviewConversationsApiPromptsPromptIdReviewPostErrors];

export type ReviewConversationsApiPromptsPromptIdReviewPostResponses = {
    /**
     * Successful Response
     */
    200: ReviewResponse;
};

export type ReviewConversationsApiPromptsPromptIdReviewPostResponse = ReviewConversationsApiPromptsPromptIdReviewPostResponses[keyof ReviewConversationsApiPromptsPromptIdReviewPostResponses];

export type ListPersonasApiPromptsPromptIdPersonasGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/personas';
};

export type ListPersonasApiPromptsPromptIdPersonasGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPersonasApiPromptsPromptIdPersonasGetError = ListPersonasApiPromptsPromptIdPersonasGetErrors[keyof ListPersonasApiPromptsPromptIdPersonasGetErrors];

export type ListPersonasApiPromptsPromptIdPersonasGetResponses = {
    /**
     * Response List Personas Api Prompts  Prompt Id  Personas Get
     *
     * Successful Response
     */
    200: Array<PersonaProfileResponse>;
};

export type ListPersonasApiPromptsPromptIdPersonasGetResponse = ListPersonasApiPromptsPromptIdPersonasGetResponses[keyof ListPersonasApiPromptsPromptIdPersonasGetResponses];

export type CreatePersonaApiPromptsPromptIdPersonasPostData = {
    body: CreatePersonaRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/personas';
};

export type CreatePersonaApiPromptsPromptIdPersonasPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePersonaApiPromptsPromptIdPersonasPostError = CreatePersonaApiPromptsPromptIdPersonasPostErrors[keyof CreatePersonaApiPromptsPromptIdPersonasPostErrors];

export type CreatePersonaApiPromptsPromptIdPersonasPostResponses = {
    /**
     * Successful Response
     */
    201: PersonaProfileResponse;
};

export type CreatePersonaApiPromptsPromptIdPersonasPostResponse = CreatePersonaApiPromptsPromptIdPersonasPostResponses[keyof CreatePersonaApiPromptsPromptIdPersonasPostResponses];

export type DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Persona Id
         */
        persona_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/personas/{persona_id}';
};

export type DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteError = DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteErrors[keyof DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteErrors];

export type DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteResponse = DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteResponses[keyof DeletePersonaApiPromptsPromptIdPersonasPersonaIdDeleteResponses];

export type UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutData = {
    body: UpdatePersonaRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Persona Id
         */
        persona_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/personas/{persona_id}';
};

export type UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutError = UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutErrors[keyof UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutErrors];

export type UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutResponses = {
    /**
     * Successful Response
     */
    200: PersonaProfileResponse;
};

export type UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutResponse = UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutResponses[keyof UpdatePersonaApiPromptsPromptIdPersonasPersonaIdPutResponses];

export type ExportPersonasApiPromptsPromptIdPersonasExportGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/personas/export';
};

export type ExportPersonasApiPromptsPromptIdPersonasExportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportPersonasApiPromptsPromptIdPersonasExportGetError = ExportPersonasApiPromptsPromptIdPersonasExportGetErrors[keyof ExportPersonasApiPromptsPromptIdPersonasExportGetErrors];

export type ExportPersonasApiPromptsPromptIdPersonasExportGetResponses = {
    /**
     * Response Export Personas Api Prompts  Prompt Id  Personas Export Get
     *
     * Successful Response
     */
    200: Array<PersonaProfileResponse>;
};

export type ExportPersonasApiPromptsPromptIdPersonasExportGetResponse = ExportPersonasApiPromptsPromptIdPersonasExportGetResponses[keyof ExportPersonasApiPromptsPromptIdPersonasExportGetResponses];

export type ImportPersonasApiPromptsPromptIdPersonasImportPostData = {
    /**
     * Body
     */
    body: Array<CreatePersonaRequest>;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/personas/import';
};

export type ImportPersonasApiPromptsPromptIdPersonasImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportPersonasApiPromptsPromptIdPersonasImportPostError = ImportPersonasApiPromptsPromptIdPersonasImportPostErrors[keyof ImportPersonasApiPromptsPromptIdPersonasImportPostErrors];

export type ImportPersonasApiPromptsPromptIdPersonasImportPostResponses = {
    /**
     * Successful Response
     */
    200: ImportPersonasResponse;
};

export type ImportPersonasApiPromptsPromptIdPersonasImportPostResponse = ImportPersonasApiPromptsPromptIdPersonasImportPostResponses[keyof ImportPersonasApiPromptsPromptIdPersonasImportPostResponses];

export type GetSettingsApiSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/';
};

export type GetSettingsApiSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: SettingsResponse;
};

export type GetSettingsApiSettingsGetResponse = GetSettingsApiSettingsGetResponses[keyof GetSettingsApiSettingsGetResponses];

export type UpdateSettingsApiSettingsPutData = {
    body: SettingsUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/settings/';
};

export type UpdateSettingsApiSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingsApiSettingsPutError = UpdateSettingsApiSettingsPutErrors[keyof UpdateSettingsApiSettingsPutErrors];

export type UpdateSettingsApiSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: SettingsResponse;
};

export type UpdateSettingsApiSettingsPutResponse = UpdateSettingsApiSettingsPutResponses[keyof UpdateSettingsApiSettingsPutResponses];

export type GetDefaultsApiSettingsDefaultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/defaults';
};

export type GetDefaultsApiSettingsDefaultsGetResponses = {
    /**
     * Successful Response
     */
    200: SettingsResponse;
};

export type GetDefaultsApiSettingsDefaultsGetResponse = GetDefaultsApiSettingsDefaultsGetResponses[keyof GetDefaultsApiSettingsDefaultsGetResponses];

export type TestConnectionApiSettingsTestConnectionPostData = {
    body: TestConnectionRequest;
    path?: never;
    query?: never;
    url: '/api/settings/test-connection';
};

export type TestConnectionApiSettingsTestConnectionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestConnectionApiSettingsTestConnectionPostError = TestConnectionApiSettingsTestConnectionPostErrors[keyof TestConnectionApiSettingsTestConnectionPostErrors];

export type TestConnectionApiSettingsTestConnectionPostResponses = {
    /**
     * Successful Response
     */
    200: TestConnectionResponse;
};

export type TestConnectionApiSettingsTestConnectionPostResponse = TestConnectionApiSettingsTestConnectionPostResponses[keyof TestConnectionApiSettingsTestConnectionPostResponses];

export type ListPresetsApiPresetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: string | null;
    };
    url: '/api/presets';
};

export type ListPresetsApiPresetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPresetsApiPresetsGetError = ListPresetsApiPresetsGetErrors[keyof ListPresetsApiPresetsGetErrors];

export type ListPresetsApiPresetsGetResponses = {
    /**
     * Response List Presets Api Presets Get
     *
     * Successful Response
     */
    200: Array<PresetResponse>;
};

export type ListPresetsApiPresetsGetResponse = ListPresetsApiPresetsGetResponses[keyof ListPresetsApiPresetsGetResponses];

export type CreatePresetApiPresetsPostData = {
    body: CreatePresetRequest;
    path?: never;
    query?: never;
    url: '/api/presets';
};

export type CreatePresetApiPresetsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePresetApiPresetsPostError = CreatePresetApiPresetsPostErrors[keyof CreatePresetApiPresetsPostErrors];

export type CreatePresetApiPresetsPostResponses = {
    /**
     * Successful Response
     */
    201: PresetResponse;
};

export type CreatePresetApiPresetsPostResponse = CreatePresetApiPresetsPostResponses[keyof CreatePresetApiPresetsPostResponses];

export type DeletePresetApiPresetsPresetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Preset Id
         */
        preset_id: number;
    };
    query?: never;
    url: '/api/presets/{preset_id}';
};

export type DeletePresetApiPresetsPresetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePresetApiPresetsPresetIdDeleteError = DeletePresetApiPresetsPresetIdDeleteErrors[keyof DeletePresetApiPresetsPresetIdDeleteErrors];

export type DeletePresetApiPresetsPresetIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePresetApiPresetsPresetIdDeleteResponse = DeletePresetApiPresetsPresetIdDeleteResponses[keyof DeletePresetApiPresetsPresetIdDeleteResponses];

export type GetPresetApiPresetsPresetIdGetData = {
    body?: never;
    path: {
        /**
         * Preset Id
         */
        preset_id: number;
    };
    query?: never;
    url: '/api/presets/{preset_id}';
};

export type GetPresetApiPresetsPresetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPresetApiPresetsPresetIdGetError = GetPresetApiPresetsPresetIdGetErrors[keyof GetPresetApiPresetsPresetIdGetErrors];

export type GetPresetApiPresetsPresetIdGetResponses = {
    /**
     * Successful Response
     */
    200: PresetResponse;
};

export type GetPresetApiPresetsPresetIdGetResponse = GetPresetApiPresetsPresetIdGetResponses[keyof GetPresetApiPresetsPresetIdGetResponses];

export type UpdatePresetApiPresetsPresetIdPutData = {
    body: UpdatePresetRequest;
    path: {
        /**
         * Preset Id
         */
        preset_id: number;
    };
    query?: never;
    url: '/api/presets/{preset_id}';
};

export type UpdatePresetApiPresetsPresetIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePresetApiPresetsPresetIdPutError = UpdatePresetApiPresetsPresetIdPutErrors[keyof UpdatePresetApiPresetsPresetIdPutErrors];

export type UpdatePresetApiPresetsPresetIdPutResponses = {
    /**
     * Successful Response
     */
    200: PresetResponse;
};

export type UpdatePresetApiPresetsPresetIdPutResponse = UpdatePresetApiPresetsPresetIdPutResponses[keyof UpdatePresetApiPresetsPresetIdPutResponses];

export type SetDefaultApiPresetsPresetIdDefaultPutData = {
    body?: never;
    path: {
        /**
         * Preset Id
         */
        preset_id: number;
    };
    query?: never;
    url: '/api/presets/{preset_id}/default';
};

export type SetDefaultApiPresetsPresetIdDefaultPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetDefaultApiPresetsPresetIdDefaultPutError = SetDefaultApiPresetsPresetIdDefaultPutErrors[keyof SetDefaultApiPresetsPresetIdDefaultPutErrors];

export type SetDefaultApiPresetsPresetIdDefaultPutResponses = {
    /**
     * Successful Response
     */
    200: PresetResponse;
};

export type SetDefaultApiPresetsPresetIdDefaultPutResponse = SetDefaultApiPresetsPresetIdDefaultPutResponses[keyof SetDefaultApiPresetsPresetIdDefaultPutResponses];

export type GetVariablesApiPromptsPromptIdVariablesGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/variables';
};

export type GetVariablesApiPromptsPromptIdVariablesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVariablesApiPromptsPromptIdVariablesGetError = GetVariablesApiPromptsPromptIdVariablesGetErrors[keyof GetVariablesApiPromptsPromptIdVariablesGetErrors];

export type GetVariablesApiPromptsPromptIdVariablesGetResponses = {
    /**
     * Successful Response
     */
    200: PlaygroundVariablesResponse;
};

export type GetVariablesApiPromptsPromptIdVariablesGetResponse = GetVariablesApiPromptsPromptIdVariablesGetResponses[keyof GetVariablesApiPromptsPromptIdVariablesGetResponses];

export type SaveVariablesApiPromptsPromptIdVariablesPutData = {
    body: PlaygroundVariablesUpdateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/variables';
};

export type SaveVariablesApiPromptsPromptIdVariablesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveVariablesApiPromptsPromptIdVariablesPutError = SaveVariablesApiPromptsPromptIdVariablesPutErrors[keyof SaveVariablesApiPromptsPromptIdVariablesPutErrors];

export type SaveVariablesApiPromptsPromptIdVariablesPutResponses = {
    /**
     * Successful Response
     */
    200: PlaygroundVariablesResponse;
};

export type SaveVariablesApiPromptsPromptIdVariablesPutResponse = SaveVariablesApiPromptsPromptIdVariablesPutResponses[keyof SaveVariablesApiPromptsPromptIdVariablesPutResponses];

export type GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/playground-config';
};

export type GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetError = GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetErrors[keyof GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetErrors];

export type GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetResponses = {
    /**
     * Successful Response
     */
    200: PlaygroundConfigResponse;
};

export type GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetResponse = GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetResponses[keyof GetPlaygroundConfigApiPromptsPromptIdPlaygroundConfigGetResponses];

export type UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutData = {
    body: PlaygroundConfigUpdateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/playground-config';
};

export type UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutError = UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutErrors[keyof UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutErrors];

export type UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutResponses = {
    /**
     * Successful Response
     */
    200: PlaygroundConfigResponse;
};

export type UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutResponse = UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutResponses[keyof UpdatePlaygroundConfigApiPromptsPromptIdPlaygroundConfigPutResponses];

export type ChatApiPromptsPromptIdChatPostData = {
    body: ChatRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/chat';
};

export type ChatApiPromptsPromptIdChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiPromptsPromptIdChatPostError = ChatApiPromptsPromptIdChatPostErrors[keyof ChatApiPromptsPromptIdChatPostErrors];

export type ChatApiPromptsPromptIdChatPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFormatGuidesApiPromptsPromptIdFormatGuidesGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/format-guides';
};

export type ListFormatGuidesApiPromptsPromptIdFormatGuidesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFormatGuidesApiPromptsPromptIdFormatGuidesGetError = ListFormatGuidesApiPromptsPromptIdFormatGuidesGetErrors[keyof ListFormatGuidesApiPromptsPromptIdFormatGuidesGetErrors];

export type ListFormatGuidesApiPromptsPromptIdFormatGuidesGetResponses = {
    /**
     * Response List Format Guides Api Prompts  Prompt Id  Format Guides Get
     *
     * Successful Response
     */
    200: Array<FormatGuideResponse>;
};

export type ListFormatGuidesApiPromptsPromptIdFormatGuidesGetResponse = ListFormatGuidesApiPromptsPromptIdFormatGuidesGetResponses[keyof ListFormatGuidesApiPromptsPromptIdFormatGuidesGetResponses];

export type DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Tool Name
         */
        tool_name: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/format-guides/{tool_name}';
};

export type DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteError = DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteErrors[keyof DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteErrors];

export type DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteResponses = {
    /**
     * Response Delete Format Guide Api Prompts  Prompt Id  Format Guides  Tool Name  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteResponse = DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteResponses[keyof DeleteFormatGuideApiPromptsPromptIdFormatGuidesToolNameDeleteResponses];

export type UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutData = {
    /**
     * Examples
     */
    body: Array<string>;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
        /**
         * Tool Name
         */
        tool_name: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/format-guides/{tool_name}';
};

export type UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutError = UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutErrors[keyof UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutErrors];

export type UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutResponses = {
    /**
     * Successful Response
     */
    200: FormatGuideResponse;
};

export type UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutResponse = UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutResponses[keyof UpsertFormatGuideApiPromptsPromptIdFormatGuidesToolNamePutResponses];

export type GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostData = {
    body: GenerateSampleRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: string;
    };
    query?: never;
    url: '/api/prompts/{prompt_id}/format-guides/generate-sample';
};

export type GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostError = GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostErrors[keyof GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostErrors];

export type GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostResponses = {
    /**
     * Successful Response
     */
    200: GenerateSampleResponse;
};

export type GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostResponse = GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostResponses[keyof GenerateSampleApiPromptsPromptIdFormatGuidesGenerateSamplePostResponses];
